### ISSUE TITLE
"Help Wanted"  regarding Energygap

### ISSUE THREAD

**Issue by sitanshubhunia** [gashawmg/Avalon-fingerprints-for-machine-learning#1]
Thanks for https://youtu.be/cSqOt-u0_sE

I am a software developer.  Wants to gather knowledge in Cheminformatics.
How to calculate Energygap from SMILES ?
Is there were any way in RDKit ?

**Comment by gashawmg** [comment]
As far as I know, energy gaps are calculated using computational chemistry software such as https://gaussian.com/ and ORCA Forum - Portal 

| 
| 
|  | 
ORCA Forum - Portal


 |

 |

 |


I believe ORCA is free for academic purposes. I do not think RDKit has quantum mechanical calculation capability. 
I hope that helps!Gashaw
 

    On Wednesday, January 11, 2023 at 12:22:27 PM CST, sitanshubhunia ***@***.***> wrote:  
 
 


Thanks for https://youtu.be/cSqOt-u0_sE

I am a software developer. Wants to gather knowledge in Cheminformatics.
How to calculate Energygap from SMILES ?
Is there were any way in RDKit ?

**Comment by sitanshubhunia** [comment]
@gashawmg Thanks🙏
